nopCommerce_3.90/Plugins/Qixol.Plugin.Widgets.Promo/Controllers/PromoWidgetAdminController.cs
using Nop.Services.Configuration;
using Nop.Services.Localization;
using Nop.Services.Media;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Kendoui;
using Nop.Web.Framework.Mvc;
using Qixol.Nop.Promo.Core.Domain;
using Qixol.Nop.Promo.Core.Domain.Promo;
using Qixol.Nop.Promo.Core.Domain.Banner;
using Qixol.Nop.Promo.Services.Promo;
using Qixol.Nop.Promo.Services.Banner;
using Qixol.Plugin.Widgets.Promo.Domain;
using Qixol.Plugin.Widgets.Promo.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web.Mvc;
using Nop.Web.Framework.Themes;
using Qixol.Plugin.Widgets.Promo.Extensions;
using Qixol.Plugin.Widgets.Promo.Services;

namespace Qixol.Plugin.Widgets.Promo.Controllers
{
    [AdminAuthorize]
    public partial class PromoWidgetAdminController : BasePluginController
    {
        #region fields 

        private readonly IPromoPictureService _promoPictureService;
        private readonly IPictureService _pictureService;
        private readonly ILocalizationService _localizationService;
        private readonly PromoWidgetSettings _widgetSettings;
        private readonly ISettingService _settingService;
        private readonly IPromoBannerService _promoBannerService;
        private readonly IThemeContext _themeContext;
        private readonly IProductPromotionService _productPromotionsService;

        #endregion

        #region constructor

        public PromoWidgetAdminController(
                            ILocalizationService localizationService,
                            IPromoPictureService promoPictureService,
                            IPictureService pictureService,
                            PromoWidgetSettings widgetSettings,
                            ISettingService settingService,
                            IPromoBannerService promoBannerService,
                            IThemeContext themeContext,
                            IProductPromotionService productPromotionsService)
        {
            this._localizationService = localizationService;
            this._promoPictureService = promoPictureService;
            this._pictureService = pictureService;
            this._widgetSettings = widgetSettings;
            this._settingService = settingService;
            this._promoBannerService = promoBannerService;
            this._themeContext = themeContext;
            this._productPromotionsService = productPromotionsService;
        }

        #endregion

        #region Methods

        [ChildActionOnly]
        public ActionResult Configure(int? selectTab)
        {
            var model = new WidgetConfigModel();

            model.SelectedTab = selectTab.HasValue ? selectTab.Value : 0;
            model.ShowPromotionDetailsOnProductPage = _widgetSettings.ShowPromoDetailsOnProductPage;
            model.ShowStickersInCatalogue = _widgetSettings.ShowStickersInCatalogue;
            model.ShowStickersInProductPage = _widgetSettings.ShowStickersInProductPage;
            model.ProductPagePromoDetailsWidgetZone = _widgetSettings.ProductPagePromoDetailsWidgetZone;

            model.AddPictureModel.PromoTypes = new List<SelectListItem>();
            model.AddPictureModel.PromoTypes.Add(new SelectListItem() { Value = PromotionTypeName.BuyOneGetOneFree, Text = _localizationService.GetResource("Plugins.Misc.QixolPromo.PromoType.BOGOF") });
            model.AddPictureModel.PromoTypes.Add(new SelectListItem() { Value = PromotionTypeName.BuyOneGetOneReduced, Text = _localizationService.GetResource("Plugins.Misc.QixolPromo.PromoType.BOGOR") });
            model.AddPictureModel.PromoTypes.Add(new SelectListItem() { Value = PromotionTypeName.Bundle, Text = _localizationService.GetResource("Plugins.Misc.QixolPromo.PromoType.BUNDLE") });
            model.AddPictureModel.PromoTypes.Add(new SelectListItem() { Value = PromotionTypeName.Deal, Text = _localizationService.GetResource("Plugins.Misc.QixolPromo.PromoType.DEAL") });
            model.AddPictureModel.PromoTypes.Add(new SelectListItem() { Value = PromotionTypeName.ProductsReduction, Text = _localizationService.GetResource("Plugins.Misc.QixolPromo.PromoType.PRODUCTSREDUCTION") });
            model.AddPictureModel.PromoTypes.Add(new SelectListItem() { Value = PromotionTypeName.Multiple_Promos, Text = _localizationService.GetResource("Plugins.Misc.QixolPromo.PromoType.MULTIPLE") });
            model.AddPictureModel.PromoTypes.Add(new SelectListItem() { Value = PromotionTypeName.FreeProduct, Text = _localizationService.GetResource("Plugins.Misc.QixolPromo.PromoType.FREEPRODUCT") });
            model.AddPictureModel.PromoTypes.Add(new SelectListItem() { Value = PromotionTypeName.IssueCoupon, Text = _localizationService.GetResource("Plugins.Misc.QixolPromo.PromoType.ISSUECOUPON") });
            model.AddPictureModel.PromoTypes.Add(new SelectListItem() { Value = PromotionTypeName.IssuePoints, Text = _localizationService.GetResource("Plugins.Misc.QixolPromo.PromoType.ISSUEPOINTS") });

            model.AddPromoBannerModel.AvailableTransitionTypes = new List<SelectListItem>();
            model.AddPromoBannerModel.AvailableTransitionTypes.Add(new SelectListItem() { Value = NivoTransition.SLICEDOWN.TransitionType, Text = _localizationService.GetResource(NivoTransition.SLICEDOWN.ResourceName) });
            model.AddPromoBannerModel.AvailableTransitionTypes.Add(new SelectListItem() { Value = NivoTransition.SLICEDOWNLEFT.TransitionType, Text = _localizationService.GetResource(NivoTransition.SLICEDOWNLEFT.ResourceName) });
            model.AddPromoBannerModel.AvailableTransitionTypes.Add(new SelectListItem() { Value = NivoTransition.SLICEUP.TransitionType, Text = _localizationService.GetResource(NivoTransition.SLICEUP.ResourceName) });
            model.AddPromoBannerModel.AvailableTransitionTypes.Add(new SelectListItem() { Value = NivoTransition.SLICEUPLEFT.TransitionType, Text = _localizationService.GetResource(NivoTransition.SLICEUPLEFT.ResourceName) });
            model.AddPromoBannerModel.AvailableTransitionTypes.Add(new SelectListItem() { Value = NivoTransition.SLICEUPDOWN.TransitionType, Text = _localizationService.GetResource(NivoTransition.SLICEUPDOWN.ResourceName) });
            model.AddPromoBannerModel.AvailableTransitionTypes.Add(new SelectListItem() { Value = NivoTransition.SLICEUPDOWNLEFT.TransitionType, Text = _localizationService.GetResource(NivoTransition.SLICEUPDOWNLEFT.ResourceName) });
            model.AddPromoBannerModel.AvailableTransitionTypes.Add(new SelectListItem() { Value = NivoTransition.FOLD.TransitionType, Text = _localizationService.GetResource(NivoTransition.FOLD.ResourceName) });
            model.AddPromoBannerModel.AvailableTransitionTypes.Add(new SelectListItem() { Value = NivoTransition.FADE.TransitionType, Text = _localizationService.GetResource(NivoTransition.FADE.ResourceName) });
            model.AddPromoBannerModel.AvailableTransitionTypes.Add(new SelectListItem() { Value = NivoTransition.RANDOM.TransitionType, Text = _localizationService.GetResource(NivoTransition.RANDOM.ResourceName) });
            model.AddPromoBannerModel.AvailableTransitionTypes.Add(new SelectListItem() { Value = NivoTransition.SLIDEINRIGHT.TransitionType, Text = _localizationService.GetResource(NivoTransition.SLIDEINRIGHT.ResourceName) });
            model.AddPromoBannerModel.AvailableTransitionTypes.Add(new SelectListItem() { Value = NivoTransition.SLIDEINLEFT.TransitionType, Text = _localizationService.GetResource(NivoTransition.SLIDEINLEFT.ResourceName) });
            model.AddPromoBannerModel.AvailableTransitionTypes.Add(new SelectListItem() { Value = NivoTransition.BOXRANDOM.TransitionType, Text = _localizationService.GetResource(NivoTransition.BOXRANDOM.ResourceName) });
            model.AddPromoBannerModel.AvailableTransitionTypes.Add(new SelectListItem() { Value = NivoTransition.BOXRAIN.TransitionType, Text = _localizationService.GetResource(NivoTransition.BOXRAIN.ResourceName) });
            model.AddPromoBannerModel.AvailableTransitionTypes.Add(new SelectListItem() { Value = NivoTransition.BOXRAINREVERSE.TransitionType, Text = _localizationService.GetResource(NivoTransition.BOXRAINREVERSE.ResourceName) });
            model.AddPromoBannerModel.AvailableTransitionTypes.Add(new SelectListItem() { Value = NivoTransition.BOXRAINGROW.TransitionType, Text = _localizationService.GetResource(NivoTransition.BOXRAINGROW.ResourceName) });
            model.AddPromoBannerModel.AvailableTransitionTypes.Add(new SelectListItem() { Value = NivoTransition.BOXRAINGROWREVERSE.TransitionType, Text = _localizationService.GetResource(NivoTransition.BOXRAINGROWREVERSE.ResourceName) });

            model.AddPromoBannerModel.AvailableTransitionTypes.Add(new SelectListItem() { Value = NivoTransition.STACKHORIZONTAL.TransitionType, Text = _localizationService.GetResource(NivoTransition.STACKHORIZONTAL.ResourceName) });
            model.AddPromoBannerModel.AvailableTransitionTypes.Add(new SelectListItem() { Value = NivoTransition.STACKVERTICAL.TransitionType, Text = _localizationService.GetResource(NivoTransition.STACKVERTICAL.ResourceName) });

            var widgetZones = WidgetZonesHelper.GetWidgetZonesForProductPromos();
            model.ProductPagePromoDetailsWidgetZonesList = widgetZones.Select(wz => new SelectListItem() { Text = wz.DisplayName, Value = wz.Name }).OrderBy(ob => ob.Text).ToList();

            if (string.IsNullOrEmpty(model.ProductPagePromoDetailsWidgetZone))
            {
                var defaultWidgetZone = widgetZones.Where(z => z.DefaultForProductPromos).FirstOrDefault();
                if (defaultWidgetZone != null)
                    model.ProductPagePromoDetailsWidgetZone = defaultWidgetZone.Name;
            }


            return View("~/Plugins/Widgets.QixolPromo/Views/Admin/Configure.cshtml", model);
        }

        [HttpPost]
        [ChildActionOnly]
        [FormValueRequired("save")]

nopCommerce_3.90/Plugins/Qixol.Plugin.Widgets.Promo/Views/Admin/_BannersList.cshtml
@model PromoBannerModel

<div class="panel-group">
    <div class="panel panel-default">
        <div class="panel-heading">
            @T("Plugins.Widgets.QixolPromo.Banners")
        </div>
        <div class="panel-body">
            <div id="promobanners-grid"></div>
        </div>
    </div>
</div>

<div class="panel-group">
    <div class="panel panel-default">
        <div class="panel-heading">
            @T("Plugins.Widgets.QixolPromo.PromoBanner.AddNewTitle")
        </div>
        <div class="panel-body">
            <div class="form-group">
                <div class="col-md-3">
                    @Html.NopLabelFor(model => model.Name)
                </div>
                <div class="col-md-9">
                    @Html.NopEditorFor(model => model.Name)
                    @Html.ValidationMessageFor(model => model.Name)
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-3">
                    @Html.NopLabelFor(model => model.TransitionType)
                </div>
                <div class="col-md-9">
                    @*@Html.NopEditorFor(model => model.TransitionType)*@
                    @Html.NopDropDownListFor(model => model.TransitionType, Model.AvailableTransitionTypes)
                    @Html.ValidationMessageFor(model => model.TransitionType)
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-3">
                    @Html.NopLabelFor(model => model.Enabled)
                </div>
                <div class="col-md-9">
                    @Html.NopEditorFor(model => model.Enabled)
                    @Html.ValidationMessageFor(model => model.Enabled)
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-3">
                    &nbsp;
                </div>
                <div class="col-md-9">
                    <input type="button" id="addPromoBanner" class="btn bg-blue" value="@T("Plugins.Widgets.QixolPromo.PromoBanner.AddButton")" />
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    function initializeBannersGrid() {
        $("#promobanners-grid").kendoGrid({
            dataSource: {
                type: "json",
                transport: {
                    read: {
                        url: "@Html.Raw(Url.Action("BannersList", "PromoWidgetAdmin"))",
                        type: "POST",
                        dataType: "json"
                    },
                    update: {
                        url: "@Html.Raw(Url.Action("BannerEdit", "PromoWidgetAdmin"))",
                        type: "POST",
                        dataType: "json"
                    },
                    destroy: {
                        url: "@Html.Raw(Url.Action("BannerDelete", "PromoWidgetAdmin"))",
                        type: "POST",
                        dataType: "json"
                    }
                },
                schema: {
                    data: "Data",
                    total: "Total",
                    errors: "Errors",
                    model: {
                        id: "Id",
                        fields: {
                            Name: { editable: true, type: "string" },
                            Enabled: { editable: true, type: "boolean" },
                            TransitionType: { defaultValue: { TransitionTypeID: 1, TransitionTypeName: "Slice Down" } }, @* not sure this is actually used but may be needed for the field name definitions *@
                            Configure: { editable: false, type: "string" }
                        }
                    }
                },
                requestEnd: function (e) {
                    if (e.type == "destroy" || e.type == 'update') {
                        this.read();
                    }
                },
                error: function (e) {
                    display_kendoui_grid_error(e);
                    // Cancel the changes
                    this.cancelChanges();
                },
                serverPaging: true,
                serverFiltering: true,
                serverSorting: true
            },
            pageable: {
                refresh: true,
                numeric: false,
                previousNext: false,
                info: false
            },
            editable: {
                confirmation: true,
                mode: "inline"
            },
            scrollable: false,
            columns: [{
                field: "Name",
                title: "@T("Plugins.Widgets.QixolPromo.PromoBanner.Name")"
            }, {
                field: "Enabled",
                title: "@T("Plugins.Widgets.QixolPromo.PromoBanner.Enabled")",
                width: 100,
                headerAttributes: { style: "text-align:center" },
                attributes: { style: "text-align:center" },
                template: '<i class="fa # if (Enabled) { # fa-check true-icon # } else { # fa-close false-icon # } #" />'
            }, {
                field: "TransitionType",
                title: "@T("Plugins.Widgets.QixolPromo.PromoBanner.TransitionType")",
                width: 350,
                headerAttributes: { style: "text-align:center" },
                attributes: { style: "text-align:center" },
                editor: transitionTypeDropDownEditor,
                template: "#=TransitionTypeName#"
            }, {
                field: "Configure",
                title: "@T("Admin.ContentManagement.Widgets.Configure")",
                headerAttributes: { style: "text-align:center" },
                attributes: { style: "text-align:center" },
                width: 150,
                template: '<a href="/Admin/PromoBanner/Admin/Banner/Index?id=#=Id#">@T("Admin.ContentManagement.Widgets.Configure")</a>'
            }, {
                command: [{
                    name: "edit",
                    text: "@T("Admin.Common.Edit")"
                }, {
                    name: "destroy",
                    text: "@T("Admin.Common.Delete")"
                }],
                headerAttributes: { style: "text-align:center" },
                attributes: { style: "text-align:center" },
                width: 200
            }]
        });

        $("#promobanners-grid table").on("keydown", "tr", function (e) {
            var grid = $("#promobanners-grid").data("kendoGrid");
            var code = (e.keyCode ? e.keyCode : e.which);
            if (code == 13) { // "Enter" keycode
                setTimeout(function () {
                    $('.k-grid-update').focus();
                    grid.saveRow();
                });
                return false;
            }
        });
    }

    function transitionTypeDropDownEditor(container, options) {
        $('<input required data-text-field="TransitionTypeName" data-value-field="TransitionTypeID" data-bind="value:' + options.field + '"/>')
            .appendTo(container)
            .kendoDropDownList({
                autoBind: false,
                dataSource: {
                    type: "json",
                    transport: {
                        read: {
                            url: "@Html.Raw(Url.Action("TransitionTypes", "PromoWidgetAdmin"))",
                            type: "POST",
                            dataType: "json"
                        }
                    }
                }
            });
    }

    $(document).ready(function () {

        initializeBannersGrid();

        $('#addPromoBanner').click(function () {
            var name = $("#@Html.FieldIdFor(model => model.Name)").val();
            var isEnabled = document.getElementById("@Html.FieldIdFor(model => model.Enabled)").checked;
            var transitionType = $('#@Html.FieldIdFor(model => model.TransitionType)').val();

            if (name == "") {
                alert('@T("Plugins.Widgets.QixolPromo.PromoBanner.Validation.Msg.1")');
                return;
            }

            $('#addPromoBanner').attr('disabled', true);
            $.ajax({
                cache: false,
                type: "POST",
                url: "@(Url.Action("BannerAdd", "PromoWidgetAdmin"))",
                data: { "name": name, "enabled": isEnabled, "transitionType": transitionType },
                success: function (data) {
                    var grid = $("#promobanners-grid");
                    grid.data('kendoGrid').dataSource.read();

                    // Reset the inputs back..  Currently doesn't clear the picture though.
                    $('#addPromoBanner').attr('disabled', false);
                    $("#@Html.FieldIdFor(model => model.Name)").val("");
                    $("#@Html.FieldIdFor(model => model.Enabled)").val("true");
                    $('#@Html.FieldIdFor(model => model.TransitionType)').val('');
                    document.getElementById("@Html.FieldIdFor(model => model.Enabled)").checked = false;
                },
                error: function (xhr, ajaxOptions, thrownError) {
                    alert('@T("Plugins.Widgets.QixolPromo.PromoBanner.Failure.Msg")');
                    $('#addPromoBanner').attr('disabled', false);
                }
            });
        });
    });
</script>

nopCommerce_3.90/Plugins/Qixol.Plugin.Widgets.Promo/Views/Admin/_PicturesList.cshtml
@model PromoAddPictureModel

<style>
    .disabled {
        color: silver;
    }
</style>

<div class="panel-group">
    <div class="panel panel-default">
        <div class="panel-heading">
            @T("Plugins.Widgets.QixolPromo.Pictures")
        </div>
        <div class="panel-body">
            <div id="promopictures-grid"></div>
        </div>
    </div>
</div>

<div class="panel-group">
    <div class="panel panel-default">
        <div class="panel-heading">
            @T("Admin.Catalog.Products.Pictures.AddNew")
        </div>
        <div class="panel-body">
            <div class="form-group">
                <div class="col-md-3">
                    @Html.NopLabelFor(model => model.PictureId)
                </div>
                <div class="col-md-9">
                    @Html.NopEditorFor(model => model.PictureId)
                    @Html.ValidationMessageFor(model => model.PictureId)
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-3">
                    @Html.NopLabelFor(model => model.IsDefaultForType)
                </div>
                <div class="col-md-9">
                    @Html.NopEditorFor(model => model.IsDefaultForType)
                    @Html.ValidationMessageFor(model => model.IsDefaultForType)
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-3">
                    @Html.NopLabelFor(model => model.DefaultForTypeName)
                </div>
                <div class="col-md-9">
                    @Html.NopDropDownListFor(model => model.DefaultForTypeName, Model.PromoTypes, new { disabled = "disabled" })
                    @Html.ValidationMessageFor(model => model.DefaultForTypeName)
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-3">
                    @Html.NopLabelFor(model => model.PromoReference)
                </div>
                <div class="col-md-9">
                    @Html.NopEditorFor(model => model.PromoReference)
                    @Html.ValidationMessageFor(model => model.PromoReference)
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-3">
                    &nbsp;
                </div>
                <div class="col-md-9">
                    <input type="submit" id="addPromoPicture" class="btn bg-blue" value="@T("Plugins.Widgets.QixolPromo.PromoPicture.AddButton")" />
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    function onDataBound() {
        //Selects all delete buttons
        $("#promopictures-grid tbody tr .k-grid-delete").each(function () {
            var currentDataItem = $("#promopictures-grid").data("kendoGrid").dataItem($(this).closest("tr"));

            //Check in the current dataItem if the row is the system default, and if so remove it.
            if (currentDataItem.SystemDefault == true) {
                $(this).remove();
            }
        })
    }

    function initializeGrid() {
        $("#promopictures-grid").kendoGrid({
            dataSource: {
                type: "json",
                transport: {
                    read: {
                        url: "@Html.Raw(Url.Action("PicturesList", "PromoWidgetAdmin"))",
                        type: "POST",
                        dataType: "json"
                    },
                    destroy: {
                        url: "@Html.Raw(Url.Action("PictureDelete", "PromoWidgetAdmin"))",
                        type: "POST",
                        dataType: "json"
                    }
                },
                schema: {
                    data: "Data",
                    total: "Total",
                    errors: "Errors",
                    model: {
                        id: "Id",
                        fields: {
                            PictureUrl: { editable: false, type: "string" },
                            DefaultForTypeName: { editable: false, type: "string" },
                            PromoReference: { editable: false, type: "string" },
                            SystemDefault: { editable: false, type: "bool" },
                            DefaultForTypeDisplay: { editable: false, type: "string" }
                        }
                    }
                },
                requestEnd: function (e) {
                    if (e.type == "destroy") {
                        this.read();
                    }
                },
                error: function (e) {
                    display_kendoui_grid_error(e);
                    // Cancel the changes
                    this.cancelChanges();
                },
                serverPaging: true,
                serverFiltering: true,
                serverSorting: true
            },
            dataBound: function (e) {
                onDataBound();
            },
            pageable: {
                refresh: true,
                numeric: false,
                previousNext: false,
                info: false
            },
            editable: {
                confirmation: true,
                mode: "inline"
            },
            scrollable: false,
            columns: [{
                field: "PictureUrl",
                title: "@T("Plugins.Widgets.QixolPromo.PromoPicture.Picture")",
                template: '<a href="#=PictureUrl#" target="_blank"><img alt="#=PictureId#" src="#=PictureUrl#" width="80" /><a/>',
                width: 100
            }, {
                field: "DefaultForTypeDisplay",
                title: "@T("Plugins.Widgets.QixolPromo.PromoPicture.DefaultForType.ColumnHeader")",
                width: 150
            }, {
                field: "PromoReference",
                title: "@T("Plugins.Widgets.QixolPromo.PromoPicture.PromoReference")",
                width: 150
            }, {
                command: [{
                    name: "destroy",
                    text: "@T("Admin.Common.Delete")"
                }],
                headerAttributes: { style: "text-align:center" },
                attributes: { style: "text-align:center" },
                width: 50
            }]
        });
    }

    function addPromoPicture(e) {
            var pictureId = $("#@Html.FieldIdFor(model => model.PictureId)").val();
            var defaultForType = document.getElementById("@Html.FieldIdFor(model => model.IsDefaultForType)").checked;
            var promoRef = $("#@Html.FieldIdFor(model => model.PromoReference)").val();
            var promoType = $("#@Html.FieldIdFor(model => model.DefaultForTypeName)").val();

            if (pictureId == 0) {
                alert('@T("Plugins.Widgets.QixolPromo.PromoPicture.Validation.Msg.1")');
                return;
            }

            if (defaultForType == false && promoRef == "") {
                alert("@T("Plugins.Widgets.QixolPromo.PromoPicture.Validation.Msg.2")");
                return;
            }

            if (defaultForType == true && promoType == "") {
                alert("@T("Plugins.Widgets.QixolPromo.PromoPicture.Validation.Msg.3")");
                return;
            }

            $('#addPromoPicture').attr('disabled', true);
            $.ajax({
                cache: false,
                type: "POST",
                url: "@(Url.Action("PictureAdd", "PromoWidgetAdmin"))",
                data: { "pictureId": pictureId, "defaultForType": defaultForType, "promoRef": promoRef, "promoType": promoType },
            success: function (data) {
                var grid = $("#promopictures-grid");
                grid.data('kendoGrid').dataSource.read();

                // Reset the inputs..  Currently doesn't clear the picture though.
                $('#addPromoPicture').attr('disabled', false);
                $("#@Html.FieldIdFor(model => model.PictureId)").val(0);
                $("#@Html.FieldIdFor(model => model.PromoReference)").val("");
                $("#@Html.FieldIdFor(model => model.IsDefaultForType)").prop('checked', false);
            $('#@Html.FieldIdFor(model => model.DefaultForTypeName)').prop('disabled', true);
            $('label[for="@Html.FieldIdFor(model => model.DefaultForTypeName)"]').toggleClass('disabled', true);
            $('#@Html.FieldIdFor(model => model.PromoReference)').prop('disabled', false);
            $('label[for="@Html.FieldIdFor(model => model.PromoReference)"]').toggleClass('disabled', false);
            },
            error: function (xhr, ajaxOptions, thrownError) {
                alert('@T("Plugins.Widgets.QixolPromo.PromoPicture.Failure.Msg")');
                $('#addPromoPicture').attr('disabled', false);
            }
        });
    }

    $(document).ready(function () {
        initializeGrid();

        $('#addPromoPicture').click(function () {
            addPromoPicture(this);
        });

        // "disable" label for default type drop down
        $('label[for="@Html.FieldIdFor(model => model.DefaultForTypeName)"]').toggleClass('disabled', true);

        $('#@Html.FieldIdFor(m => m.IsDefaultForType)').change(function () {
            $('#@Html.FieldIdFor(model => model.DefaultForTypeName)').prop('disabled', !$(this).prop('checked'));
            $('label[for="@Html.FieldIdFor(model => model.DefaultForTypeName)"]').toggleClass('disabled', !$(this).prop('checked'));
            $('#@Html.FieldIdFor(model => model.PromoReference)').prop('disabled', $(this).prop('checked'));
            $('label[for="@Html.FieldIdFor(model => model.PromoReference)"]').toggleClass('disabled', $(this).prop('checked'));
        });
    });

</script>

@*
    <script type="text/javascript">

        $(document).ready(function () {

            $('#addPromoPicture').click(function () {
                var pictureId = $("#@Html.FieldIdFor(model => model.PictureId)").val();
                var defaultForType = document.getElementById("@Html.FieldIdFor(model => model.IsDefaultForType)").checked;
                var promoRef = $("#@Html.FieldIdFor(model => model.PromoReference)").val();
                var promoType = $("#@Html.FieldIdFor(model => model.DefaultForTypeName)").val();

                if (pictureId == 0) {
                    alert('@T("Plugins.Widgets.QixolPromo.PromoPicture.Validation.Msg.1")');
                    return;
                }

                if (defaultForType == false && promoRef == "") {
                    alert("@T("Plugins.Widgets.QixolPromo.PromoPicture.Validation.Msg.2")");
                    return;
                }

                if (defaultForType == true && promoType == "") {
                    alert("@T("Plugins.Widgets.QixolPromo.PromoPicture.Validation.Msg.3")");
                    return;
                }

                $('#addPromoPicture').attr('disabled', true);
                $.ajax({
                    cache: false,
                    type: "POST",
                    url: "@(Url.Action("PictureAdd", "PromoWidgetAdmin"))",
                    data: { "pictureId": pictureId, "defaultForType": defaultForType, "promoRef": promoRef, "promoType": promoType },
                success: function (data) {
                    var grid = $("#promopictures-grid");
                    grid.data('kendoGrid').dataSource.read();

                    // Reset the inputs back..  Currently doesn't clear the picture though.
                    $('#addPromoPicture').attr('disabled', false);
                    $("#@Html.FieldIdFor(model => model.PictureId)").val(0);
                    $("#@Html.FieldIdFor(model => model.PromoReference)").val("");
                    document.getElementById("@Html.FieldIdFor(model => model.IsDefaultForType)").checked = false;
                    enableItems("@Html.FieldIdFor(model => model.DefaultForTypeName)", false);
                    enableItems("@Html.FieldIdFor(model => model.PromoReference)", true);
                },
                error: function (xhr, ajaxOptions, thrownError) {
                    alert('@T("Plugins.Widgets.QixolPromo.PromoPicture.Failure.Msg")');
                    $('#addPromoPicture').attr('disabled', false);
                }
            });
        });
        });
    </script>
*@