nopCommerce_3.90/Plugins/Qixol.Plugin.Misc.QixolPromotions/Models/Checkout/MissedPromotionBaseModel.cs
using Nop.Web.Models.Catalog;
using Nop.Web.Models.ShoppingCart;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Qixol.Plugin.Misc.Promo.Models.Checkout
{
    public abstract partial class MissedPromotionBaseModel
    {
        private IList<MissedPromotionCriteriaModel> _criteria;
        private IList<ShoppingCartModel.ShoppingCartItemModel> _matchedCartItemModels;
        private IList<PromoProductOverviewModel> _unmatchedProductOverviewModels;
        private IList<CategorySimpleModel> _categorySimpleModels;

        public string PromotionImageUrl { get; set; }
        public string SaveFrom { get; set; }
        public string PromotionName { get; set; }

        public IList<MissedPromotionCriteriaModel> Criteria
        {
            get
            {
                return _criteria ?? (_criteria = new List<MissedPromotionCriteriaModel>());
            }
            set
            {
                _criteria = value;
            }
        }

        public IList<ShoppingCartModel.ShoppingCartItemModel> MatchedCartItemModels
        {
            get
            {
                return _matchedCartItemModels ?? (_matchedCartItemModels = new List<ShoppingCartModel.ShoppingCartItemModel>());
            }
            set
            {
                _matchedCartItemModels = value;
            }
        }

        public IList<PromoProductOverviewModel> UnmatchedProductOverviewModels
        {
            get
            {
                return _unmatchedProductOverviewModels ?? (_unmatchedProductOverviewModels = new List<PromoProductOverviewModel>());
            }
            set
            {
                _unmatchedProductOverviewModels = value;
            }
        }

        public IList<CategorySimpleModel> CategorySimpleModels
        {
            get
            {
                return _categorySimpleModels ?? (_categorySimpleModels = new List<CategorySimpleModel>());
            }
            set
            {
                _categorySimpleModels = value;
            }
        }

        public partial class MissedPromotionCriteriaModel
        {
        }
    }
}

nopCommerce_3.90/Plugins/Qixol.Plugin.Misc.QixolPromotions/Models/Checkout/MissedPromotionBasketReductionModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Qixol.Plugin.Misc.Promo.Models.Checkout
{
    public partial class MissedPromotionBasketReductionModel : MissedPromotionBaseModel
    {
    }
}

nopCommerce_3.90/Plugins/Qixol.Plugin.Misc.QixolPromotions/Models/Checkout/MissedPromotionBogofModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Qixol.Plugin.Misc.Promo.Models.Checkout
{
    public partial class MissedPromotionBogofModel : MissedPromotionBaseModel
    {
    }
}

nopCommerce_3.90/Plugins/Qixol.Plugin.Misc.QixolPromotions/Models/Checkout/MissedPromotionBogorModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Qixol.Plugin.Misc.Promo.Models.Checkout
{
    public partial class MissedPromotionBogorModel : MissedPromotionBaseModel
    {
    }
}

nopCommerce_3.90/Plugins/Qixol.Plugin.Misc.QixolPromotions/Models/Checkout/MissedPromotionBundleModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Qixol.Plugin.Misc.Promo.Models.Checkout
{
    public partial class MissedPromotionBundleModel : MissedPromotionBaseModel
    {
    }
}

nopCommerce_3.90/Plugins/Qixol.Plugin.Misc.QixolPromotions/Models/Checkout/MissedPromotionDealModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Qixol.Plugin.Misc.Promo.Models.Checkout
{
    public partial class MissedPromotionDealModel : MissedPromotionBaseModel
    {
    }
}

nopCommerce_3.90/Plugins/Qixol.Plugin.Misc.QixolPromotions/Models/Checkout/MissedPromotionDeliveryModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Qixol.Plugin.Misc.Promo.Models.Checkout
{
    public partial class MissedPromotionDeliveryModel : MissedPromotionBaseModel
    {
    }
}

nopCommerce_3.90/Plugins/Qixol.Plugin.Misc.QixolPromotions/Models/Checkout/MissedPromotionFreeProductModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Qixol.Plugin.Misc.Promo.Models.Checkout
{
    public partial class MissedPromotionFreeProductModel : MissedPromotionBaseModel
    {
    }
}

nopCommerce_3.90/Plugins/Qixol.Plugin.Misc.QixolPromotions/Models/Checkout/MissedPromotionIssueCouponCodeModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Qixol.Plugin.Misc.Promo.Models.Checkout
{
    public partial class MissedPromotionCouponCodeModel : MissedPromotionBaseModel
    {
    }
}

nopCommerce_3.90/Plugins/Qixol.Plugin.Misc.QixolPromotions/Models/Checkout/MissedPromotionIssuePointsModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Qixol.Plugin.Misc.Promo.Models.Checkout
{
    public partial class MissedPromotionIssuePointsModel : MissedPromotionBaseModel
    {
    }
}

nopCommerce_3.90/Plugins/Qixol.Plugin.Misc.QixolPromotions/Models/Checkout/MissedPromotionProductReductionModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Qixol.Plugin.Misc.Promo.Models.Checkout
{
    public partial class MissedPromotionProductReductionModel : MissedPromotionBaseModel
    {
    }
}

nopCommerce_3.90/Plugins/Qixol.Plugin.Misc.QixolPromotions/Models/Checkout/MissedPromotionUnknownModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Qixol.Plugin.Misc.Promo.Models.Checkout
{
    public partial class MissedPromotionUnknownModel : MissedPromotionBaseModel
    {
    }
}

nopCommerce_3.90/Plugins/Qixol.Plugin.Misc.QixolPromotions/Models/Checkout/PromoCheckoutProgressModel.cs
using global::Nop.Web.Framework.Mvc;

namespace Qixol.Plugin.Misc.Promo.Models.Checkout
{
    public class PromoCheckoutProgressModel : global::Nop.Web.Models.Checkout.CheckoutProgressModel
    {
        public PromoCheckoutProgressStep PromoCheckoutProgressStep { get; set; }

        public bool ShowMissedPromotions { get; set; }
    }

    public enum PromoCheckoutProgressStep
    {
        Cart,
        Address,
        Shipping,
        Payment,
        Confirm,
        Complete,
        MissedPromotions
    }
}

nopCommerce_3.90/Plugins/Qixol.Plugin.Misc.QixolPromotions/Models/Checkout/PromoOnePageCheckoutModel.cs
using global::Nop.Web.Framework.Mvc;

namespace Qixol.Plugin.Misc.Promo.Models.Checkout
{
    public class PromoOnePageCheckoutModel : BaseNopModel
    {
        public PromoOnePageCheckoutModel()
        {

        }

        public bool DisableBillingAddressCheckoutStep { get; set; }
        public bool ShippingRequired { get; set; }
        public bool ShowMissedPromotions { get; set; }
    }
}

nopCommerce_3.90/Plugins/Qixol.Plugin.Misc.QixolPromotions/Controllers/PromoCheckoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Nop.Core;
using Nop.Core.Domain.Common;
using Nop.Core.Domain.Customers;
using Nop.Core.Domain.Orders;
using Nop.Core.Domain.Payments;
using Nop.Core.Domain.Shipping;
using Nop.Core.Plugins;
using Nop.Services.Common;
using Nop.Services.Customers;
using Nop.Services.Directory;
using Nop.Services.Localization;
using Nop.Services.Logging;
using Nop.Services.Orders;
using Nop.Services.Payments;
using Nop.Services.Shipping;
using Nop.Web.Extensions;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Security;
using Nop.Web.Models.Checkout;
using Qixol.Nop.Promo.Services.Promo;
using Qixol.Promo.Integration.Lib.Basket;
using Qixol.Nop.Promo.Core.Domain.Promo;

using Nop.Web.Controllers;
using Nop.Web.Models.ShoppingCart;
using Nop.Services.Seo;
using Nop.Services.Media;
using Qixol.Plugin.Misc.Promo.Models.Checkout;
using global::Nop.Web.Models.Catalog;
using System.Xml.Linq;
using Qixol.Nop.Promo.Core.Domain.ProductAttributeConfig;
using Nop.Core.Domain.Catalog;
using Nop.Core.Infrastructure;
using Qixol.Plugin.Misc.Promo.Factories;
using Nop.Web.Factories;

namespace Qixol.Plugin.Misc.Promo.Controllers
{
    [NopHttpsRequirement(SslRequirement.Yes)]
    public partial class PromoCheckoutController : global::Nop.Web.Controllers.CheckoutController
    {
        #region Fields

        private readonly ICheckoutModelFactory _checkoutModelFactory;
        private readonly IMissedPromotionsModelFactory _missedPromotionsModelFactory;

        private readonly IWorkContext _workContext;
        private readonly IStoreContext _storeContext;
        private readonly IShoppingCartService _shoppingCartService;
        private readonly ILocalizationService _localizationService;
        private readonly IOrderProcessingService _orderProcessingService;
        private readonly ICustomerService _customerService;
        private readonly IGenericAttributeService _genericAttributeService;
        private readonly ICountryService _countryService;
        private readonly IStateProvinceService _stateProvinceService;
        private readonly IShippingService _shippingService;
        private readonly IPaymentService _paymentService;
        private readonly IPluginFinder _pluginFinder;
        private readonly IOrderTotalCalculationService _orderTotalCalculationService;
        private readonly ILogger _logger;
        private readonly IOrderService _orderService;
        private readonly IWebHelper _webHelper;
        private readonly HttpContextBase _httpContext; 
        private readonly IAddressAttributeParser _addressAttributeParser;
        private readonly IAddressAttributeService _addressAttributeService;

        private readonly OrderSettings _orderSettings;
        private readonly RewardPointsSettings _rewardPointsSettings;
        private readonly PaymentSettings _paymentSettings;
        private readonly ShippingSettings _shippingSettings;
        private readonly AddressSettings _addressSettings;
        private readonly CustomerSettings _customerSettings;

        private readonly PromoSettings _promoSettings;
        private readonly IPromoService _promoService;
        private readonly IPromoUtilities _promoUtilities;

        #endregion

		#region Ctor

        public PromoCheckoutController(ICheckoutModelFactory checkoutModelFactory,
            IMissedPromotionsModelFactory missedPromotionsModelFactory,
            IWorkContext workContext,
            IStoreContext storeContext,
            IShoppingCartService shoppingCartService, 
            ILocalizationService localizationService, 
            IOrderProcessingService orderProcessingService,
            ICustomerService customerService, 
            IGenericAttributeService genericAttributeService,
            ICountryService countryService,
            IStateProvinceService stateProvinceService,
            IShippingService shippingService, 
            IPaymentService paymentService,
            IPluginFinder pluginFinder,
            IOrderTotalCalculationService orderTotalCalculationService,
            ILogger logger,
            IOrderService orderService,
            IWebHelper webHelper,
            HttpContextBase httpContext,
            IAddressAttributeParser addressAttributeParser,
            IAddressAttributeService addressAttributeService,
            OrderSettings orderSettings, 
            RewardPointsSettings rewardPointsSettings,
            PaymentSettings paymentSettings,
            ShippingSettings shippingSettings,
            AddressSettings addressSettings,
            CustomerSettings customerSettings,
            PromoSettings promoSettings,
            IPromoService promoService,
            IPromoUtilities promoUtilities)
            : base(checkoutModelFactory, workContext, storeContext,
                    shoppingCartService, localizationService,
                    orderProcessingService, customerService,
                    genericAttributeService, countryService, stateProvinceService,
                    shippingService, paymentService, pluginFinder,
                    orderTotalCalculationService, logger, orderService, webHelper, httpContext,
                    addressAttributeParser, addressAttributeService,
                    orderSettings, rewardPointsSettings,
                    paymentSettings, shippingSettings, addressSettings, customerSettings)
        {
            this._checkoutModelFactory = checkoutModelFactory;
            this._missedPromotionsModelFactory = missedPromotionsModelFactory;

            this._workContext = workContext;
            this._storeContext = storeContext;
            this._shoppingCartService = shoppingCartService;
            this._localizationService = localizationService;
            this._orderProcessingService = orderProcessingService;
            this._customerService = customerService;
            this._genericAttributeService = genericAttributeService;
            this._countryService = countryService;
            this._stateProvinceService = stateProvinceService;
            this._shippingService = shippingService;
            this._paymentService = paymentService;
            this._pluginFinder = pluginFinder;
            this._orderTotalCalculationService = orderTotalCalculationService;
            this._logger = logger;
            this._orderService = orderService;
            this._webHelper = webHelper;
            this._httpContext = httpContext;
            this._addressAttributeParser = addressAttributeParser;
            this._addressAttributeService = addressAttributeService;

            this._orderSettings = orderSettings;
            this._rewardPointsSettings = rewardPointsSettings;
            this._paymentSettings = paymentSettings;
            this._shippingSettings = shippingSettings;
            this._addressSettings = addressSettings;
            this._customerSettings = customerSettings;

            this._promoSettings = promoSettings;
            this._promoService = promoService;
            this._promoUtilities = promoUtilities;
        }

        #endregion

        #region Utilities

        public ActionResult ContinueShopping()
        {
            var returnUrl = _workContext.CurrentCustomer.GetAttribute<string>(SystemCustomerAttributeNames.LastContinueShoppingPage, _storeContext.CurrentStore.Id);
            if (String.IsNullOrEmpty(returnUrl))
            {
                returnUrl = Url.RouteUrl("HomePage");
            }

            return Json(new
            {
                continue_shopping_url = returnUrl
            });
        }

        #endregion

        #region public action methods

        public ActionResult PromoIndex()
        {
            var cart = _workContext.CurrentCustomer.ShoppingCartItems
                .Where(sci => sci.ShoppingCartType == ShoppingCartType.ShoppingCart)
                .LimitPerStore(_storeContext.CurrentStore.Id)
                .ToList();
            if (cart.Count == 0)
                return RedirectToRoute("ShoppingCart");

            if ((_workContext.CurrentCustomer.IsGuest() && !_orderSettings.AnonymousCheckoutAllowed))
                return new HttpUnauthorizedResult();

            //reset checkout data
            _customerService.ResetCheckoutData(_workContext.CurrentCustomer, _storeContext.CurrentStore.Id);

            if (!_promoSettings.Enabled || !_promoSettings.ShowMissedPromotions)
            {
                if (_orderSettings.OnePageCheckoutEnabled)
                {
                    return RedirectToRoute("CheckoutOnePage");
                }
                else
                {
                    return RedirectToRoute("CheckoutBillingAddress");
                }
            }
            else
            {
                if (_orderSettings.OnePageCheckoutEnabled)
                {
                    return RedirectToRoute("PromoCheckoutOnePage");
                }
                else
                {
                    return RedirectToRoute("PromoCheckoutMissedPromotions");
                }
            }
        }

        public ActionResult MissedPromotions()
        {
            var cart = _workContext.CurrentCustomer.ShoppingCartItems
                .Where(sci => sci.ShoppingCartType == ShoppingCartType.ShoppingCart)
                .LimitPerStore(_storeContext.CurrentStore.Id)
                .ToList();

            if (cart.Count == 0)
                return RedirectToRoute("ShoppingCart");

            if (_orderSettings.OnePageCheckoutEnabled)
                return RedirectToRoute("CheckoutOnePage");

            if (!_promoSettings.Enabled || !_promoSettings.ShowMissedPromotions)
                return RedirectToRoute("CheckoutBillingAddress");

            if ((_workContext.CurrentCustomer.IsGuest() && !_orderSettings.AnonymousCheckoutAllowed))
                return new HttpUnauthorizedResult();

nopCommerce_3.90/Plugins/Qixol.Plugin.Misc.QixolPromotions/Views/Checkout/CheckoutProgress.cshtml
@model PromoCheckoutProgressModel

<div class="order-progress">
    <ul>
        @Html.Widget("checkout_progress_before")
        <li class="active-step">
            <a @(Model.PromoCheckoutProgressStep != PromoCheckoutProgressStep.Complete ?
                    @Html.Raw(string.Format(" href=\"{0}\"", Url.RouteUrl("ShoppingCart"))) :
                    null)>@T("Checkout.Progress.Cart")</a>
        </li>
        @if (Model.ShowMissedPromotions)
        {
        <li @(Model.PromoCheckoutProgressStep == PromoCheckoutProgressStep.MissedPromotions ||
                Model.PromoCheckoutProgressStep == PromoCheckoutProgressStep.Address ||
                Model.PromoCheckoutProgressStep == PromoCheckoutProgressStep.Shipping ||
                Model.PromoCheckoutProgressStep == PromoCheckoutProgressStep.Payment ||
                Model.PromoCheckoutProgressStep == PromoCheckoutProgressStep.Confirm ||
                Model.PromoCheckoutProgressStep == PromoCheckoutProgressStep.Complete ? @Html.Raw(" class=\"active-step\"") : @Html.Raw(" class=\"inactive-step\""))>
            <a @(Model.PromoCheckoutProgressStep != PromoCheckoutProgressStep.Cart && Model.PromoCheckoutProgressStep != PromoCheckoutProgressStep.Complete ?
                 @Html.Raw(string.Format(" href=\"{0}\"", Url.RouteUrl("PromoCheckoutMissedPromotions"))) :
                 null)>@T("Plugins.Misc.QixolPromo.MissedPromotion(s)")</a>
        </li>
        }
        <li @(Model.PromoCheckoutProgressStep == PromoCheckoutProgressStep.Address ||
            Model.PromoCheckoutProgressStep == PromoCheckoutProgressStep.Shipping ||
            Model.PromoCheckoutProgressStep == PromoCheckoutProgressStep.Payment ||
            Model.PromoCheckoutProgressStep == PromoCheckoutProgressStep.Confirm ||
            Model.PromoCheckoutProgressStep == PromoCheckoutProgressStep.Complete ? @Html.Raw(" class=\"active-step\"") : @Html.Raw(" class=\"inactive-step\""))>
            <a @(Model.PromoCheckoutProgressStep != PromoCheckoutProgressStep.Cart &&
                Model.PromoCheckoutProgressStep != PromoCheckoutProgressStep.Complete ?
                    @Html.Raw(string.Format(" href=\"{0}\"", Url.RouteUrl("CheckoutBillingAddress"))) :
                    null)>@T("Checkout.Progress.Address")</a>
        </li>
        <li @(Model.PromoCheckoutProgressStep == PromoCheckoutProgressStep.Shipping ||
            Model.PromoCheckoutProgressStep == PromoCheckoutProgressStep.Payment ||
            Model.PromoCheckoutProgressStep == PromoCheckoutProgressStep.Confirm ||
            Model.PromoCheckoutProgressStep == PromoCheckoutProgressStep.Complete ? @Html.Raw(" class=\"active-step\"") : @Html.Raw(" class=\"inactive-step\""))>
            <a @(Model.PromoCheckoutProgressStep != PromoCheckoutProgressStep.Cart &&
                Model.PromoCheckoutProgressStep != PromoCheckoutProgressStep.Address &&
                Model.PromoCheckoutProgressStep != PromoCheckoutProgressStep.Complete ?
                    @Html.Raw(string.Format(" href=\"{0}\"", Url.RouteUrl("CheckoutShippingMethod"))) :
                    null)>@T("Checkout.Progress.Shipping")</a>
        </li>
        <li @(Model.PromoCheckoutProgressStep == PromoCheckoutProgressStep.Payment ||
            Model.PromoCheckoutProgressStep == PromoCheckoutProgressStep.Confirm ||
            Model.PromoCheckoutProgressStep == PromoCheckoutProgressStep.Complete ? @Html.Raw(" class=\"active-step\"") : @Html.Raw(" class=\"inactive-step\""))>
            <a @(Model.PromoCheckoutProgressStep != PromoCheckoutProgressStep.Cart &&
                Model.PromoCheckoutProgressStep != PromoCheckoutProgressStep.Address &&
                Model.PromoCheckoutProgressStep != PromoCheckoutProgressStep.Shipping &&
                Model.PromoCheckoutProgressStep != PromoCheckoutProgressStep.Complete ?
                    @Html.Raw(string.Format(" href=\"{0}\"", Url.RouteUrl("CheckoutPaymentMethod"))) :
                    null)>@T("Checkout.Progress.Payment")</a>
        </li>
        <li @(Model.PromoCheckoutProgressStep == PromoCheckoutProgressStep.Confirm ||
            Model.PromoCheckoutProgressStep == PromoCheckoutProgressStep.Complete ? @Html.Raw(" class=\"active-step\"") : @Html.Raw(" class=\"inactive-step\""))>
            <a @(Model.PromoCheckoutProgressStep != PromoCheckoutProgressStep.Cart &&
                Model.PromoCheckoutProgressStep != PromoCheckoutProgressStep.Address &&
                Model.PromoCheckoutProgressStep != PromoCheckoutProgressStep.Shipping &&
                Model.PromoCheckoutProgressStep != PromoCheckoutProgressStep.Payment &&
                Model.PromoCheckoutProgressStep != PromoCheckoutProgressStep.Complete ?
                    @Html.Raw(string.Format(" href=\"{0}\"", Url.RouteUrl("CheckoutConfirm"))) :
                    null)>@T("Checkout.Progress.Confirm")</a>
        </li>
        <li @(Model.PromoCheckoutProgressStep == PromoCheckoutProgressStep.Complete ? @Html.Raw(" class=\"active-step\"") : @Html.Raw(" class=\"inactive-step\""))>
            <a>@T("Checkout.Progress.Complete")</a>
        </li>
        @Html.Widget("checkout_progress_after")
    </ul>
</div>

nopCommerce_3.90/Plugins/Qixol.Plugin.Misc.QixolPromotions/Views/Checkout/MissedPromotions.cshtml
@model MissedPromotionsModel

@{
    Layout = "~/Views/Shared/_ColumnsOne.cshtml";

    //title
    Html.AddTitleParts(T("Plugins.Misc.QixolPromo.MissedPromotions.PageTitle").Text);

}

<div class="page checkout-page missed-promotions-page">
    @Html.Action("PromoCheckoutProgress", "PromoCheckout", new { step = PromoCheckoutProgressStep.MissedPromotions, ShowMissedPromotions = true })
    <div class="page-title">
        <h1>@T("Plugins.Misc.QixolPromo.MissedPromotions.PageTitle")</h1>
    </div>
    <div class="page-body checkout-data">
        <div class="section missed-promotions">
            @Html.Partial("MissedPromotionsSummary", Model)
        </div>
        @if (true)
            {
                <div class="buttons">
                    <input type="button" title="@T("ShoppingCart.ContinueShopping")" value="@T("ShoppingCart.ContinueShopping")" onclick="continueShopping();" class="button-1 continue-shopping-button" />
                    <input type="button" name="nextstep" value="@T("Checkout.NextButton")" class="button-1 missed-promotions-next-step-button" style="width: 221px;" onclick="window.location='@Url.RouteUrl("CheckoutBillingAddress")';" />
                </div>
            }
        <div class="section order-summary">
            <div class="title">
                <strong>@T("Checkout.OrderSummary")</strong>
            </div>
            @Html.Action("OrderSummary", "ShoppingCart")
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        PromoAjaxCart.init();
    });

    function continueShopping() {
        $.ajax({
            cache: false,
            url: '@Url.RouteUrl("PromoContinueShopping")',
            type: 'post',
            success: function(response) { window.location = response.continue_shopping_url; },
            complete: function() { window.location = '@Url.RouteUrl("HomePage")'},
            error: function () { window.location = '@Url.RouteUrl("HomePage")' }
        });
    }

</script>

nopCommerce_3.90/Plugins/Qixol.Plugin.Misc.QixolPromotions/Views/Checkout/MissedPromotionsSummary.cshtml
@model MissedPromotionsModel

@using Qixol.Plugin.Misc.Promo.Models.Checkout;
@using global::Nop.Web.Models.Catalog;
@using global::Nop.Core.Domain.Tax;
@using global::Nop.Core;
@using global::Nop.Core.Infrastructure;
@using global::Nop.Web.Models.ShoppingCart;

@{
    Html.AddScriptParts(ResourceLocation.Head, "~/Plugins/Misc.QixolPromo/Scripts/promo.ajaxcart.js");
}

<div class="table-wrapper">
    <table class="missed-promotions">
        <colgroup>
            <col style="width: 100px;" />
            <col style="width: 375px;"/>
            <col />
        </colgroup>
        <thead>
            <tr>
                <th class="product-picture">
                    @T("ShoppingCart.Image")
                </th>
                <th class="product">
                    @T("Plugins.Misc.QixolPromo.MissedPromotion(s)")
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @if (Model.MissedPromotions.Count == 0)
            {
                <tr><td></td><td>There are no missed promotions</td><td></td></tr>
            }
            else
            {
                @Html.DisplayFor(mp => Model.MissedPromotions);
            }
        </tbody>
    </table>
</div>
<script>
    $(document).ready(function () {
        PromoAjaxCart.init();
    });

    function continueShopping() {
        $.ajax({
            cache: false,
            url: '@Url.RouteUrl("PromoContinueShopping")',
            type: 'post',
            success: function(response) { window.location = response.continue_shopping_url; },
            complete: function() { window.location = '@Url.RouteUrl("HomePage")'},
            error: function () { window.location = '@Url.RouteUrl("HomePage")' }
        });
    }

</script>

nopCommerce_3.90/Plugins/Qixol.Plugin.Misc.QixolPromotions/Views/Checkout/OpcMissedPromotions.cshtml
@model MissedPromotionsModel
@using Nop.Web.Models.Checkout;
<div class="checkout-data">
    @Html.Widget("op_checkout_missed_promotions_top")
    <div class="section missed-promotions">
        @Html.Partial("MissedPromotionsSummary", Model)
    </div>
    @Html.Widget("op_checkout_missed_promotions_bottom")
</div>
@if (Model.MissedPromotions.Count == 0)
{
    <script type="text/javascript">
        $(document).ready(function () {
            MissedPromotions.next();
        });
    </script>
}

nopCommerce_3.90/Plugins/Qixol.Plugin.Misc.QixolPromotions/Views/Checkout/_UnmatchedProducts.cshtml
@model List<PromoProductOverviewModel>
@using Nop.Web.Models.Checkout;

@if (Model != null && Model.Any())
{
    <div class="item-box" style="width: 100%;">
        <table class="missed-promotion">
            <colgroup>
                <col style="width: 100px;" />
                <col />
            </colgroup>
            <thead>
                <tr>
                    <th class="product-picture">
                        @T("ShoppingCart.Image")
                    </th>
                    <th class="product">
                        @T("Plugins.Misc.QixolPromo.Product(s)")
                    </th>
                </tr>
            </thead>
            <tbody>
                @Html.DisplayFor(m => Model)
            </tbody>
        </table>
    </div>
}